requires "Object::Remote";
requires "Git::Repository";
requires "Getopt::Long::Descriptive";
requires "Capture::Tiny";
requires "Moo";
requires "File::chdir";
requires "Ask::STDIO";
requires "IO::All";
requires "curry";
